/*
 * Generated by classgen, version 1.5
 * 25.09.10 11:38
 */
package com.sc2mod.andromeda.syntaxNodes;

public interface AccessType {

  public final static int SIMPLE = 0;
  public final static int SUPER = 1;
  public final static int NATIVE = 2;
  public final static int NAMED_SUPER = 3;
  public final static int EXPRESSION = 4;
  public final static int POINTER = 5;

}
