/*
 * Generated by classgen, version 1.5
 * 25.09.10 11:38
 */
package com.sc2mod.andromeda.syntaxNodes;

public interface AssignmentType {

  public final static int POINTER = 0;
  public final static int FIELD = 1;
  public final static int ARRAY = 2;

}
