/*
 * Generated by classgen, version 1.5
 * 25.09.10 11:38
 */
package com.sc2mod.andromeda.syntaxNodes;

public class IncludedFile extends GlobalStructure {

  private SourceFile includedContent;

  public IncludedFile (SourceFile includedContent) {
    this.includedContent = includedContent;
    if (includedContent != null) includedContent.setParent(this);
  }

  public SourceFile getIncludedContent() {
    return includedContent;
  }

  public void setIncludedContent(SourceFile includedContent) {
    this.includedContent = includedContent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (includedContent != null) includedContent.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (includedContent != null) includedContent.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (includedContent != null) includedContent.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("IncludedFile(\n");
      if (includedContent != null)
        buffer.append(includedContent.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [IncludedFile]");
    return buffer.toString();
  }
}
