/*
 * Generated by classgen, version 1.5
 * 25.09.10 11:38
 */
package com.sc2mod.andromeda.syntaxNodes;

public interface LiteralType {

  public final static int INT = 0;
  public final static int FLOAT = 1;
  public final static int STRING = 2;
  public final static int NULL = 3;
  public final static int CHAR = 4;
  public final static int BOOL = 5;
  public final static int TEXT = 6;

}
