/*
 * Generated by classgen, version 1.5
 * 25.09.10 11:38
 */
package com.sc2mod.andromeda.syntaxNodes;

public interface ModifierType {

  public final static int PUBLIC = 0;
  public final static int PROTECTED = 1;
  public final static int PRIVATE = 2;
  public final static int STATIC = 3;
  public final static int ABSTRACT = 4;
  public final static int FINAL = 5;
  public final static int NATIVE = 6;
  public final static int TRANSIENT = 7;
  public final static int CONST = 8;
  public final static int OVERRIDE = 9;

}
