/*
 * Generated by classgen, version 1.5
 * 25.09.10 11:38
 */
package com.sc2mod.andromeda.syntaxNodes;

public interface TypeCategory {

  public final static int BASIC = 0;
  public final static int SIMPLE = 1;
  public final static int QUALIFIED = 2;
  public final static int ARRAY = 3;
  public final static int POINTER = 4;
  public final static int FUNCTION = 5;

}
